# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [22]:
import numpy as np
from random import randint
import random

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 
# se crea un array que contiene los numeros del 0 al 9
array_numeros = np.arange(0, 10)  # genera una secuencia de numeros desde 'inicio' hasta 'fin - 1'

print(array_numeros)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [16]:
#todo:
# se crea un array de 5 elementos, todos con valor 0
array_ceros = np.zeros(5)   # genera un array solo de ceros del tamaño indicado

# se cambia el valor del tercer elemento (indice 2) a 5
array_ceros[2] = 5


print(array_ceros)

[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo: 
# se crea una matriz de 3x3 con numeros aleatorios entre 0 y 1
matriz_aleatoria = np.random.uniform(0, 1, size=(3, 3)) 


print(matriz_aleatoria)

[[0.25272839 0.0921312  0.46722818]
 [0.85950255 0.96911765 0.97170336]
 [0.58932767 0.8929306  0.68485278]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [41]:
#todo:
arr = np.array([10, 20, 30, 40, 50])

# Se suma 5 a cada elemento del array
arr_sumado = arr + 5

# Se genera un numero aleatorio
num_aleatorio = random.randint(1, 100)

# Se multiplica todo el array por ese numero aleatorio
arr_multiplicado = arr_sumado * num_aleatorio

# Se muestran los resultados
print("Array original:", arr)
print("Array + 5:", arr_sumado)
print(f"Numero aleatorio: {num_aleatorio}")
print("Resultado de la multiplicacion:", arr_multiplicado)

Array original: [10 20 30 40 50]
Array + 5: [15 25 35 45 55]
Numero aleatorio: 13
Resultado de la multiplicacion: [195 325 455 585 715]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [45]:
#todo:
# se crea una matriz identidad 4x4
matriz_identidad = np.eye(4)

print(matriz_identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

